// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package dap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ttEOF-0]
	_ = x[ttBlank-1]
	_ = x[ttSymbol-2]
	_ = x[ttImport-3]
	_ = x[ttConstString-4]
	_ = x[ttConstNumber-5]
	_ = x[ttLeftParenthese-6]
	_ = x[ttRightParenthese-7]
	_ = x[ttLeftBracket-8]
	_ = x[ttRigthBracket-9]
	_ = x[ttLeftCurve-10]
	_ = x[ttRightCurve-11]
	_ = x[ttLineEnd-12]
	_ = x[ttDot-13]
	_ = x[ttComma-14]
	_ = x[ttVar-15]
	_ = x[ttAssign-16]
	_ = x[ttEqual-17]
	_ = x[ttGT-18]
	_ = x[ttShiftRight-19]
	_ = x[ttGTE-20]
	_ = x[ttNot-21]
	_ = x[ttNotEqual-22]
	_ = x[ttLT-23]
	_ = x[ttLTE-24]
	_ = x[ttReturn-25]
	_ = x[ttIf-26]
	_ = x[ttElse-27]
	_ = x[ttSemi-28]
	_ = x[ttAdd-29]
	_ = x[ttAddAdd-30]
	_ = x[ttSub-31]
	_ = x[ttMulti-32]
	_ = x[ttDiv-33]
}

const _TokenType_name = "ttEOFttBlankttSymbolttImportttConstStringttConstNumberttLeftParenthesettRightParenthesettLeftBracketttRigthBracketttLeftCurvettRightCurvettLineEndttDotttCommattVarttAssignttEqualttGTttShiftRightttGTEttNotttNotEqualttLTttLTEttReturnttIfttElsettSemittAddttAddAddttSubttMultittDiv"

var _TokenType_index = [...]uint16{0, 5, 12, 20, 28, 41, 54, 70, 87, 100, 114, 125, 137, 146, 151, 158, 163, 171, 178, 182, 194, 199, 204, 214, 218, 223, 231, 235, 241, 247, 252, 260, 265, 272, 277}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
